export const FETCH_CHARACTER_PENDING = 'FETCH_CHARACTER_PENDING';
export const FETCH_CHARACTER_REJECTED = 'FETCH_CHARACTER_REJECTED';
export const FETCH_CHARACTER_FULFILLED = 'FETCH_CHARACTER_FULFILLED';
