export const FETCH_CHARACTERS_PENDING = 'FETCH_CHARACTERS_PENDING';
export const FETCH_CHARACTERS_REJECTED = 'FETCH_CHARACTERS_REJECTED';
export const FETCH_CHARACTERS_FULFILLED = 'FETCH_CHARACTERS_FULFILLED';
